// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

/**
 * Protobuf type {@code AcceptRequest}
 */
public  final class AcceptRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AcceptRequest)
    AcceptRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AcceptRequest.newBuilder() to construct.
  private AcceptRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AcceptRequest() {
    proposalNumber_ = 0;
    processId_ = "";
    transactionsToAccept_ = java.util.Collections.emptyList();
    needsSync_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AcceptRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            proposalNumber_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            processId_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              transactionsToAccept_ = new java.util.ArrayList<org.cse535.proto.Transaction>();
              mutable_bitField0_ |= 0x00000008;
            }
            transactionsToAccept_.add(
                input.readMessage(org.cse535.proto.Transaction.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              syncBlocks_ = com.google.protobuf.MapField.newMapField(
                  SyncBlocksDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
            syncBlocks__ = input.readMessage(
                SyncBlocksDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            syncBlocks_.getMutableMap().put(
                syncBlocks__.getKey(), syncBlocks__.getValue());
            break;
          }
          case 48: {

            needsSync_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        transactionsToAccept_ = java.util.Collections.unmodifiableList(transactionsToAccept_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetSyncBlocks();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.AcceptRequest.class, org.cse535.proto.AcceptRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PROPOSALNUMBER_FIELD_NUMBER = 1;
  private int proposalNumber_;
  /**
   * <code>int32 proposalNumber = 1;</code>
   */
  public int getProposalNumber() {
    return proposalNumber_;
  }

  public static final int PROCESSID_FIELD_NUMBER = 2;
  private volatile java.lang.Object processId_;
  /**
   * <pre>
   * processId is Server Name initiating Accept Request
   * </pre>
   *
   * <code>string processId = 2;</code>
   */
  public java.lang.String getProcessId() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * processId is Server Name initiating Accept Request
   * </pre>
   *
   * <code>string processId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProcessIdBytes() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int TRANSACTIONSTOACCEPT_FIELD_NUMBER = 4;
  private java.util.List<org.cse535.proto.Transaction> transactionsToAccept_;
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  public java.util.List<org.cse535.proto.Transaction> getTransactionsToAcceptList() {
    return transactionsToAccept_;
  }
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getTransactionsToAcceptOrBuilderList() {
    return transactionsToAccept_;
  }
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  public int getTransactionsToAcceptCount() {
    return transactionsToAccept_.size();
  }
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  public org.cse535.proto.Transaction getTransactionsToAccept(int index) {
    return transactionsToAccept_.get(index);
  }
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  public org.cse535.proto.TransactionOrBuilder getTransactionsToAcceptOrBuilder(
      int index) {
    return transactionsToAccept_.get(index);
  }

  public static final int SYNCBLOCKS_FIELD_NUMBER = 5;
  private static final class SyncBlocksDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, org.cse535.proto.BlockOfTransactions> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, org.cse535.proto.BlockOfTransactions>newDefaultInstance(
                org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_SyncBlocksEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.cse535.proto.BlockOfTransactions.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, org.cse535.proto.BlockOfTransactions> syncBlocks_;
  private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
  internalGetSyncBlocks() {
    if (syncBlocks_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SyncBlocksDefaultEntryHolder.defaultEntry);
    }
    return syncBlocks_;
  }

  public int getSyncBlocksCount() {
    return internalGetSyncBlocks().getMap().size();
  }
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  public boolean containsSyncBlocks(
      int key) {
    
    return internalGetSyncBlocks().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSyncBlocksMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> getSyncBlocks() {
    return getSyncBlocksMap();
  }
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  public java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> getSyncBlocksMap() {
    return internalGetSyncBlocks().getMap();
  }
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  public org.cse535.proto.BlockOfTransactions getSyncBlocksOrDefault(
      int key,
      org.cse535.proto.BlockOfTransactions defaultValue) {
    
    java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> map =
        internalGetSyncBlocks().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  public org.cse535.proto.BlockOfTransactions getSyncBlocksOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> map =
        internalGetSyncBlocks().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int NEEDSSYNC_FIELD_NUMBER = 6;
  private boolean needsSync_;
  /**
   * <code>bool needsSync = 6;</code>
   */
  public boolean getNeedsSync() {
    return needsSync_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (proposalNumber_ != 0) {
      output.writeInt32(1, proposalNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processId_);
    }
    if (timestamp_ != null) {
      output.writeMessage(3, getTimestamp());
    }
    for (int i = 0; i < transactionsToAccept_.size(); i++) {
      output.writeMessage(4, transactionsToAccept_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetSyncBlocks(),
        SyncBlocksDefaultEntryHolder.defaultEntry,
        5);
    if (needsSync_ != false) {
      output.writeBool(6, needsSync_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (proposalNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, proposalNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processId_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimestamp());
    }
    for (int i = 0; i < transactionsToAccept_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, transactionsToAccept_.get(i));
    }
    for (java.util.Map.Entry<java.lang.Integer, org.cse535.proto.BlockOfTransactions> entry
         : internalGetSyncBlocks().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
      syncBlocks__ = SyncBlocksDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, syncBlocks__);
    }
    if (needsSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, needsSync_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.AcceptRequest)) {
      return super.equals(obj);
    }
    org.cse535.proto.AcceptRequest other = (org.cse535.proto.AcceptRequest) obj;

    boolean result = true;
    result = result && (getProposalNumber()
        == other.getProposalNumber());
    result = result && getProcessId()
        .equals(other.getProcessId());
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && getTimestamp()
          .equals(other.getTimestamp());
    }
    result = result && getTransactionsToAcceptList()
        .equals(other.getTransactionsToAcceptList());
    result = result && internalGetSyncBlocks().equals(
        other.internalGetSyncBlocks());
    result = result && (getNeedsSync()
        == other.getNeedsSync());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROPOSALNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getProposalNumber();
    hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessId().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (getTransactionsToAcceptCount() > 0) {
      hash = (37 * hash) + TRANSACTIONSTOACCEPT_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsToAcceptList().hashCode();
    }
    if (!internalGetSyncBlocks().getMap().isEmpty()) {
      hash = (37 * hash) + SYNCBLOCKS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSyncBlocks().hashCode();
    }
    hash = (37 * hash) + NEEDSSYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedsSync());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.AcceptRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.AcceptRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.AcceptRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AcceptRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AcceptRequest)
      org.cse535.proto.AcceptRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetSyncBlocks();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableSyncBlocks();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.AcceptRequest.class, org.cse535.proto.AcceptRequest.Builder.class);
    }

    // Construct using org.cse535.proto.AcceptRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionsToAcceptFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      proposalNumber_ = 0;

      processId_ = "";

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (transactionsToAcceptBuilder_ == null) {
        transactionsToAccept_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        transactionsToAcceptBuilder_.clear();
      }
      internalGetMutableSyncBlocks().clear();
      needsSync_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_AcceptRequest_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.AcceptRequest getDefaultInstanceForType() {
      return org.cse535.proto.AcceptRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.AcceptRequest build() {
      org.cse535.proto.AcceptRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.AcceptRequest buildPartial() {
      org.cse535.proto.AcceptRequest result = new org.cse535.proto.AcceptRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.proposalNumber_ = proposalNumber_;
      result.processId_ = processId_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (transactionsToAcceptBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          transactionsToAccept_ = java.util.Collections.unmodifiableList(transactionsToAccept_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.transactionsToAccept_ = transactionsToAccept_;
      } else {
        result.transactionsToAccept_ = transactionsToAcceptBuilder_.build();
      }
      result.syncBlocks_ = internalGetSyncBlocks();
      result.syncBlocks_.makeImmutable();
      result.needsSync_ = needsSync_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.AcceptRequest) {
        return mergeFrom((org.cse535.proto.AcceptRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.AcceptRequest other) {
      if (other == org.cse535.proto.AcceptRequest.getDefaultInstance()) return this;
      if (other.getProposalNumber() != 0) {
        setProposalNumber(other.getProposalNumber());
      }
      if (!other.getProcessId().isEmpty()) {
        processId_ = other.processId_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (transactionsToAcceptBuilder_ == null) {
        if (!other.transactionsToAccept_.isEmpty()) {
          if (transactionsToAccept_.isEmpty()) {
            transactionsToAccept_ = other.transactionsToAccept_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTransactionsToAcceptIsMutable();
            transactionsToAccept_.addAll(other.transactionsToAccept_);
          }
          onChanged();
        }
      } else {
        if (!other.transactionsToAccept_.isEmpty()) {
          if (transactionsToAcceptBuilder_.isEmpty()) {
            transactionsToAcceptBuilder_.dispose();
            transactionsToAcceptBuilder_ = null;
            transactionsToAccept_ = other.transactionsToAccept_;
            bitField0_ = (bitField0_ & ~0x00000008);
            transactionsToAcceptBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsToAcceptFieldBuilder() : null;
          } else {
            transactionsToAcceptBuilder_.addAllMessages(other.transactionsToAccept_);
          }
        }
      }
      internalGetMutableSyncBlocks().mergeFrom(
          other.internalGetSyncBlocks());
      if (other.getNeedsSync() != false) {
        setNeedsSync(other.getNeedsSync());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.AcceptRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.AcceptRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int proposalNumber_ ;
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public int getProposalNumber() {
      return proposalNumber_;
    }
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public Builder setProposalNumber(int value) {
      
      proposalNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public Builder clearProposalNumber() {
      
      proposalNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object processId_ = "";
    /**
     * <pre>
     * processId is Server Name initiating Accept Request
     * </pre>
     *
     * <code>string processId = 2;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * processId is Server Name initiating Accept Request
     * </pre>
     *
     * <code>string processId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * processId is Server Name initiating Accept Request
     * </pre>
     *
     * <code>string processId = 2;</code>
     */
    public Builder setProcessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * processId is Server Name initiating Accept Request
     * </pre>
     *
     * <code>string processId = 2;</code>
     */
    public Builder clearProcessId() {
      
      processId_ = getDefaultInstance().getProcessId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * processId is Server Name initiating Accept Request
     * </pre>
     *
     * <code>string processId = 2;</code>
     */
    public Builder setProcessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.util.List<org.cse535.proto.Transaction> transactionsToAccept_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsToAcceptIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        transactionsToAccept_ = new java.util.ArrayList<org.cse535.proto.Transaction>(transactionsToAccept_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> transactionsToAcceptBuilder_;

    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public java.util.List<org.cse535.proto.Transaction> getTransactionsToAcceptList() {
      if (transactionsToAcceptBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactionsToAccept_);
      } else {
        return transactionsToAcceptBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public int getTransactionsToAcceptCount() {
      if (transactionsToAcceptBuilder_ == null) {
        return transactionsToAccept_.size();
      } else {
        return transactionsToAcceptBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public org.cse535.proto.Transaction getTransactionsToAccept(int index) {
      if (transactionsToAcceptBuilder_ == null) {
        return transactionsToAccept_.get(index);
      } else {
        return transactionsToAcceptBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder setTransactionsToAccept(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsToAcceptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.set(index, value);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder setTransactionsToAccept(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsToAcceptBuilder_ == null) {
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsToAcceptBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder addTransactionsToAccept(org.cse535.proto.Transaction value) {
      if (transactionsToAcceptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.add(value);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder addTransactionsToAccept(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsToAcceptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.add(index, value);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder addTransactionsToAccept(
        org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsToAcceptBuilder_ == null) {
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsToAcceptBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder addTransactionsToAccept(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsToAcceptBuilder_ == null) {
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsToAcceptBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder addAllTransactionsToAccept(
        java.lang.Iterable<? extends org.cse535.proto.Transaction> values) {
      if (transactionsToAcceptBuilder_ == null) {
        ensureTransactionsToAcceptIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactionsToAccept_);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder clearTransactionsToAccept() {
      if (transactionsToAcceptBuilder_ == null) {
        transactionsToAccept_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public Builder removeTransactionsToAccept(int index) {
      if (transactionsToAcceptBuilder_ == null) {
        ensureTransactionsToAcceptIsMutable();
        transactionsToAccept_.remove(index);
        onChanged();
      } else {
        transactionsToAcceptBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder getTransactionsToAcceptBuilder(
        int index) {
      return getTransactionsToAcceptFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public org.cse535.proto.TransactionOrBuilder getTransactionsToAcceptOrBuilder(
        int index) {
      if (transactionsToAcceptBuilder_ == null) {
        return transactionsToAccept_.get(index);  } else {
        return transactionsToAcceptBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
         getTransactionsToAcceptOrBuilderList() {
      if (transactionsToAcceptBuilder_ != null) {
        return transactionsToAcceptBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactionsToAccept_);
      }
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsToAcceptBuilder() {
      return getTransactionsToAcceptFieldBuilder().addBuilder(
          org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsToAcceptBuilder(
        int index) {
      return getTransactionsToAcceptFieldBuilder().addBuilder(
          index, org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .Transaction transactionsToAccept = 4;</code>
     */
    public java.util.List<org.cse535.proto.Transaction.Builder> 
         getTransactionsToAcceptBuilderList() {
      return getTransactionsToAcceptFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> 
        getTransactionsToAcceptFieldBuilder() {
      if (transactionsToAcceptBuilder_ == null) {
        transactionsToAcceptBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder>(
                transactionsToAccept_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        transactionsToAccept_ = null;
      }
      return transactionsToAcceptBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, org.cse535.proto.BlockOfTransactions> syncBlocks_;
    private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
    internalGetSyncBlocks() {
      if (syncBlocks_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SyncBlocksDefaultEntryHolder.defaultEntry);
      }
      return syncBlocks_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
    internalGetMutableSyncBlocks() {
      onChanged();;
      if (syncBlocks_ == null) {
        syncBlocks_ = com.google.protobuf.MapField.newMapField(
            SyncBlocksDefaultEntryHolder.defaultEntry);
      }
      if (!syncBlocks_.isMutable()) {
        syncBlocks_ = syncBlocks_.copy();
      }
      return syncBlocks_;
    }

    public int getSyncBlocksCount() {
      return internalGetSyncBlocks().getMap().size();
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public boolean containsSyncBlocks(
        int key) {
      
      return internalGetSyncBlocks().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSyncBlocksMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> getSyncBlocks() {
      return getSyncBlocksMap();
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> getSyncBlocksMap() {
      return internalGetSyncBlocks().getMap();
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public org.cse535.proto.BlockOfTransactions getSyncBlocksOrDefault(
        int key,
        org.cse535.proto.BlockOfTransactions defaultValue) {
      
      java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> map =
          internalGetSyncBlocks().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public org.cse535.proto.BlockOfTransactions getSyncBlocksOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> map =
          internalGetSyncBlocks().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSyncBlocks() {
      internalGetMutableSyncBlocks().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public Builder removeSyncBlocks(
        int key) {
      
      internalGetMutableSyncBlocks().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
    getMutableSyncBlocks() {
      return internalGetMutableSyncBlocks().getMutableMap();
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */
    public Builder putSyncBlocks(
        int key,
        org.cse535.proto.BlockOfTransactions value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSyncBlocks().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * To utilize in case of missing blocks / failure of node
     * </pre>
     *
     * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
     */

    public Builder putAllSyncBlocks(
        java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions> values) {
      internalGetMutableSyncBlocks().getMutableMap()
          .putAll(values);
      return this;
    }

    private boolean needsSync_ ;
    /**
     * <code>bool needsSync = 6;</code>
     */
    public boolean getNeedsSync() {
      return needsSync_;
    }
    /**
     * <code>bool needsSync = 6;</code>
     */
    public Builder setNeedsSync(boolean value) {
      
      needsSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool needsSync = 6;</code>
     */
    public Builder clearNeedsSync() {
      
      needsSync_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AcceptRequest)
  }

  // @@protoc_insertion_point(class_scope:AcceptRequest)
  private static final org.cse535.proto.AcceptRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.AcceptRequest();
  }

  public static org.cse535.proto.AcceptRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcceptRequest>
      PARSER = new com.google.protobuf.AbstractParser<AcceptRequest>() {
    @java.lang.Override
    public AcceptRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AcceptRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AcceptRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AcceptRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.AcceptRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

