// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

/**
 * Protobuf type {@code AcceptResponse}
 */
public  final class AcceptResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AcceptResponse)
    AcceptResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AcceptResponse.newBuilder() to construct.
  private AcceptResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AcceptResponse() {
    ballotNumber_ = 0;
    success_ = false;
    acceptNum_ = 0;
    acceptVal_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AcceptResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ballotNumber_ = input.readInt32();
            break;
          }
          case 16: {

            success_ = input.readBool();
            break;
          }
          case 24: {

            acceptNum_ = input.readInt32();
            break;
          }
          case 32: {

            acceptVal_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.PaxosOuterClass.internal_static_AcceptResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.PaxosOuterClass.internal_static_AcceptResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.AcceptResponse.class, org.cse535.proto.AcceptResponse.Builder.class);
  }

  public static final int BALLOTNUMBER_FIELD_NUMBER = 1;
  private int ballotNumber_;
  /**
   * <code>int32 ballotNumber = 1;</code>
   */
  public int getBallotNumber() {
    return ballotNumber_;
  }

  public static final int SUCCESS_FIELD_NUMBER = 2;
  private boolean success_;
  /**
   * <code>bool success = 2;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int ACCEPTNUM_FIELD_NUMBER = 3;
  private int acceptNum_;
  /**
   * <code>int32 acceptNum = 3;</code>
   */
  public int getAcceptNum() {
    return acceptNum_;
  }

  public static final int ACCEPTVAL_FIELD_NUMBER = 4;
  private int acceptVal_;
  /**
   * <code>int32 acceptVal = 4;</code>
   */
  public int getAcceptVal() {
    return acceptVal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ballotNumber_ != 0) {
      output.writeInt32(1, ballotNumber_);
    }
    if (success_ != false) {
      output.writeBool(2, success_);
    }
    if (acceptNum_ != 0) {
      output.writeInt32(3, acceptNum_);
    }
    if (acceptVal_ != 0) {
      output.writeInt32(4, acceptVal_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ballotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ballotNumber_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, success_);
    }
    if (acceptNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, acceptNum_);
    }
    if (acceptVal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, acceptVal_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.AcceptResponse)) {
      return super.equals(obj);
    }
    org.cse535.proto.AcceptResponse other = (org.cse535.proto.AcceptResponse) obj;

    boolean result = true;
    result = result && (getBallotNumber()
        == other.getBallotNumber());
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (getAcceptNum()
        == other.getAcceptNum());
    result = result && (getAcceptVal()
        == other.getAcceptVal());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BALLOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getBallotNumber();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + ACCEPTNUM_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptNum();
    hash = (37 * hash) + ACCEPTVAL_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptVal();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.AcceptResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.AcceptResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.AcceptResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.AcceptResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AcceptResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AcceptResponse)
      org.cse535.proto.AcceptResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.PaxosOuterClass.internal_static_AcceptResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.PaxosOuterClass.internal_static_AcceptResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.AcceptResponse.class, org.cse535.proto.AcceptResponse.Builder.class);
    }

    // Construct using org.cse535.proto.AcceptResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ballotNumber_ = 0;

      success_ = false;

      acceptNum_ = 0;

      acceptVal_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.PaxosOuterClass.internal_static_AcceptResponse_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.AcceptResponse getDefaultInstanceForType() {
      return org.cse535.proto.AcceptResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.AcceptResponse build() {
      org.cse535.proto.AcceptResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.AcceptResponse buildPartial() {
      org.cse535.proto.AcceptResponse result = new org.cse535.proto.AcceptResponse(this);
      result.ballotNumber_ = ballotNumber_;
      result.success_ = success_;
      result.acceptNum_ = acceptNum_;
      result.acceptVal_ = acceptVal_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.AcceptResponse) {
        return mergeFrom((org.cse535.proto.AcceptResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.AcceptResponse other) {
      if (other == org.cse535.proto.AcceptResponse.getDefaultInstance()) return this;
      if (other.getBallotNumber() != 0) {
        setBallotNumber(other.getBallotNumber());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getAcceptNum() != 0) {
        setAcceptNum(other.getAcceptNum());
      }
      if (other.getAcceptVal() != 0) {
        setAcceptVal(other.getAcceptVal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.AcceptResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.AcceptResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ballotNumber_ ;
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public int getBallotNumber() {
      return ballotNumber_;
    }
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public Builder setBallotNumber(int value) {
      
      ballotNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public Builder clearBallotNumber() {
      
      ballotNumber_ = 0;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 2;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 2;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 2;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private int acceptNum_ ;
    /**
     * <code>int32 acceptNum = 3;</code>
     */
    public int getAcceptNum() {
      return acceptNum_;
    }
    /**
     * <code>int32 acceptNum = 3;</code>
     */
    public Builder setAcceptNum(int value) {
      
      acceptNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 acceptNum = 3;</code>
     */
    public Builder clearAcceptNum() {
      
      acceptNum_ = 0;
      onChanged();
      return this;
    }

    private int acceptVal_ ;
    /**
     * <code>int32 acceptVal = 4;</code>
     */
    public int getAcceptVal() {
      return acceptVal_;
    }
    /**
     * <code>int32 acceptVal = 4;</code>
     */
    public Builder setAcceptVal(int value) {
      
      acceptVal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 acceptVal = 4;</code>
     */
    public Builder clearAcceptVal() {
      
      acceptVal_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AcceptResponse)
  }

  // @@protoc_insertion_point(class_scope:AcceptResponse)
  private static final org.cse535.proto.AcceptResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.AcceptResponse();
  }

  public static org.cse535.proto.AcceptResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcceptResponse>
      PARSER = new com.google.protobuf.AbstractParser<AcceptResponse>() {
    @java.lang.Override
    public AcceptResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AcceptResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AcceptResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AcceptResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.AcceptResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

