// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface AcceptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AcceptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ballotNumber = 1;</code>
   */
  int getBallotNumber();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <code>int32 acceptNum = 3;</code>
   */
  int getAcceptNum();

  /**
   * <code>int32 acceptVal = 4;</code>
   */
  int getAcceptVal();
}
