// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

public interface AcceptRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AcceptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 proposalNumber = 1;</code>
   */
  int getProposalNumber();

  /**
   * <pre>
   * processId is Server Name initiating Accept Request
   * </pre>
   *
   * <code>string processId = 2;</code>
   */
  java.lang.String getProcessId();
  /**
   * <pre>
   * processId is Server Name initiating Accept Request
   * </pre>
   *
   * <code>string processId = 2;</code>
   */
  com.google.protobuf.ByteString
      getProcessIdBytes();

  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  java.util.List<org.cse535.proto.Transaction> 
      getTransactionsToAcceptList();
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  org.cse535.proto.Transaction getTransactionsToAccept(int index);
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  int getTransactionsToAcceptCount();
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getTransactionsToAcceptOrBuilderList();
  /**
   * <code>repeated .Transaction transactionsToAccept = 4;</code>
   */
  org.cse535.proto.TransactionOrBuilder getTransactionsToAcceptOrBuilder(
      int index);

  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */
  int getSyncBlocksCount();
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */
  boolean containsSyncBlocks(
      int key);
  /**
   * Use {@link #getSyncBlocksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
  getSyncBlocks();
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */
  java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
  getSyncBlocksMap();
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  org.cse535.proto.BlockOfTransactions getSyncBlocksOrDefault(
      int key,
      org.cse535.proto.BlockOfTransactions defaultValue);
  /**
   * <pre>
   * To utilize in case of missing blocks / failure of node
   * </pre>
   *
   * <code>map&lt;int32, .BlockOfTransactions&gt; syncBlocks = 5;</code>
   */

  org.cse535.proto.BlockOfTransactions getSyncBlocksOrThrow(
      int key);

  /**
   * <code>bool needsSync = 6;</code>
   */
  boolean getNeedsSync();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
