// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

public final class ApaxosOuterClass {
  private ApaxosOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionInputConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionInputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptRequest_SyncBlocksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptRequest_SyncBlocksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockOfTransactions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlockOfTransactions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseSnapshot_BlocksEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseSnapshot_BlocksEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseSnapshot_BalanceAfterCommitEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseSnapshot_BalanceAfterCommitEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseSnapshot_ClientBalancesAfterCommitEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseSnapshot_ClientBalancesAfterCommitEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatabaseSnapshot_TimeTakenToExecuteMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatabaseSnapshot_TimeTakenToExecuteMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeTakenMask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeTakenMask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataSaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSaveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataSaveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataGetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014apaxos.proto\032\037google/protobuf/timestam" +
      "p.proto\"c\n\026TransactionInputConfig\022\021\n\tset" +
      "Number\030\001 \001(\005\022!\n\013transaction\030\002 \001(\0132\014.Tran" +
      "saction\022\023\n\013serverNames\030\005 \003(\t\"2\n\013TxnRespo" +
      "nse\022\017\n\007success\030\001 \001(\010\022\022\n\nserverName\030\002 \001(\t" +
      "\"j\n\016PrepareRequest\022\026\n\016proposalNumber\030\001 \001" +
      "(\005\022\021\n\tprocessId\030\002 \001(\t\022-\n\ttimestamp\030\003 \001(\013" +
      "2\032.google.protobuf.Timestamp\"\327\001\n\017Prepare" +
      "Response\022\026\n\016proposalNumber\030\001 \001(\005\022\021\n\tproc" +
      "essId\030\002 \001(\t\022\"\n\014transactions\030\004 \003(\0132\014.Tran" +
      "saction\022\037\n\027AcceptNumProposalNumber\030\005 \001(\005" +
      "\022\032\n\022AcceptNumProcessId\030\006 \001(\t\022\'\n\tAcceptVa" +
      "l\030\007 \001(\0132\024.BlockOfTransactions\022\017\n\007success" +
      "\030\003 \001(\010\"\245\002\n\rAcceptRequest\022\026\n\016proposalNumb" +
      "er\030\001 \001(\005\022\021\n\tprocessId\030\002 \001(\t\022-\n\ttimestamp" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\022*\n\024tr" +
      "ansactionsToAccept\030\004 \003(\0132\014.Transaction\0222" +
      "\n\nsyncBlocks\030\005 \003(\0132\036.AcceptRequest.SyncB" +
      "locksEntry\022\021\n\tneedsSync\030\006 \001(\010\032G\n\017SyncBlo" +
      "cksEntry\022\013\n\003key\030\001 \001(\005\022#\n\005value\030\002 \001(\0132\024.B" +
      "lockOfTransactions:\0028\001\"h\n\016AcceptResponse" +
      "\022\026\n\016proposalNumber\030\001 \001(\005\022\021\n\tprocessId\030\002 " +
      "\001(\t\022\032\n\022acceptedServerName\030\003 \001(\t\022\017\n\007succe" +
      "ss\030\004 \001(\010\"\216\001\n\rCommitRequest\022\026\n\016proposalNu" +
      "mber\030\001 \001(\005\022\021\n\tprocessId\030\002 \001(\t\022#\n\005block\030\003" +
      " \001(\0132\024.BlockOfTransactions\022-\n\ttimestamp\030" +
      "\004 \001(\0132\032.google.protobuf.Timestamp\"h\n\016Com" +
      "mitResponse\022\026\n\016proposalNumber\030\001 \001(\005\022\017\n\007s" +
      "uccess\030\004 \001(\010\022\021\n\tprocessId\030\002 \001(\t\022\032\n\022accep" +
      "tedServerName\030\003 \001(\t\"\237\001\n\013Transaction\022\016\n\006s" +
      "ender\030\001 \001(\t\022\020\n\010receiver\030\002 \001(\t\022\016\n\006amount\030" +
      "\003 \001(\005\022-\n\ttimestamp\030\004 \001(\0132\032.google.protob" +
      "uf.Timestamp\022\027\n\017transactionHash\030\005 \001(\t\022\026\n" +
      "\016transactionNum\030\006 \001(\005\"\267\001\n\023BlockOfTransac" +
      "tions\022\"\n\014transactions\030\001 \003(\0132\014.Transactio" +
      "n\022\020\n\010blockNum\030\002 \001(\005\0223\n\017blockCommitTime\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\022\021\n\tbloc" +
      "kHash\030\004 \001(\t\022\016\n\006leader\030\006 \001(\t\022\022\n\ntermNumbe" +
      "r\030\005 \001(\005\"+\n\025ActivateServerRequest\022\022\n\nserv" +
      "erName\030\001 \001(\t\"=\n\026ActivateServerResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\022\n\nserverName\030\002 \001(\t\"-\n\027D" +
      "eactivateServerRequest\022\022\n\nserverName\030\001 \001" +
      "(\t\"?\n\030DeactivateServerResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\022\022\n\nserverName\030\002 \001(\t\"\035\n\014CommandIn" +
      "put\022\r\n\005input\030\001 \001(\t\"\037\n\rCommandOutput\022\016\n\006o" +
      "utput\030\001 \001(\t\"\311\n\n\020DatabaseSnapshot\022\036\n\026Acce" +
      "ptedProposalNumber\030\001 \001(\005\022\030\n\020AcceptedServ" +
      "erId\030\002 \001(\t\0229\n\033AcceptedBlockOfTransaction" +
      "s\030\003 \001(\0132\024.BlockOfTransactions\022\026\n\016Account" +
      "Balance\030\004 \001(\005\022\037\n\027CommittedAccountBalance" +
      "\030\005 \001(\005\022\037\n\027CommittedProposalNumber\030\006 \001(\005\022" +
      "-\n\006blocks\030\007 \003(\0132\035.DatabaseSnapshot.Block" +
      "sEntry\022E\n\022balanceAfterCommit\030\010 \003(\0132).Dat" +
      "abaseSnapshot.BalanceAfterCommitEntry\022S\n" +
      "\031clientBalancesAfterCommit\030\t \003(\01320.Datab" +
      "aseSnapshot.ClientBalancesAfterCommitEnt" +
      "ry\022\035\n\025transactionsProcessed\030\n \001(\005\022\035\n\025tra" +
      "nsactionsCommitted\030\013 \001(\005\022\033\n\023transactions" +
      "Aborted\030\014 \001(\005\022\035\n\025currentProposalNumber\030\r" +
      " \001(\005\022\027\n\017currentServerId\030\016 \001(\t\022:\n\031incomin" +
      "gTransactionsQueue\030\017 \003(\0132\027.TransactionIn" +
      "putConfig\022)\n\023localTransactionLog\030\020 \003(\0132\014" +
      ".Transaction\022*\n\024leaderTransactionLog\030\021 \003" +
      "(\0132\014.Transaction\022;\n\027lastPrepareAckTimest" +
      "amp\030\022 \001(\0132\032.google.protobuf.Timestamp\022\034\n" +
      "\024lastPrepareAckServer\030\023 \001(\t\022:\n\026lastAccep" +
      "tAckTimestamp\030\024 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\0227\n\023lastCommitTimestamp\030\025 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022 \n\030processedTra" +
      "nsactionsSet\030\026 \003(\005\022K\n\025timeTakenToExecute" +
      "Map\030\027 \003(\0132,.DatabaseSnapshot.TimeTakenTo" +
      "ExecuteMapEntry\022&\n\036LeaderBalanceAfterTra" +
      "nsactions\030\030 \001(\005\032C\n\013BlocksEntry\022\013\n\003key\030\001 " +
      "\001(\005\022#\n\005value\030\002 \001(\0132\024.BlockOfTransactions" +
      ":\0028\001\0329\n\027BalanceAfterCommitEntry\022\013\n\003key\030\001" +
      " \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\032@\n\036ClientBalance" +
      "sAfterCommitEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\005:\0028\001\032L\n\032TimeTakenToExecuteMapEntry\022" +
      "\013\n\003key\030\001 \001(\005\022\035\n\005value\030\002 \001(\0132\016.TimeTakenM" +
      "ask:\0028\001\"3\n\rTimeTakenMask\022\021\n\tstartTime\030\001 " +
      "\001(\003\022\017\n\007endTime\030\002 \001(\003\"J\n\017DataSaveRequest\022" +
      "\022\n\nserverName\030\001 \001(\t\022#\n\010snapshot\030\002 \001(\0132\021." +
      "DatabaseSnapshot\"#\n\020DataSaveResponse\022\017\n\007" +
      "success\030\001 \001(\010\"$\n\016DataGetRequest\022\022\n\nserve" +
      "rName\030\001 \001(\t\"G\n\017DataGetResponse\022#\n\010snapsh" +
      "ot\030\001 \001(\0132\021.DatabaseSnapshot\022\017\n\007success\030\002" +
      " \001(\0102\222\001\n\006Apaxos\022.\n\007prepare\022\017.PrepareRequ" +
      "est\032\020.PrepareResponse\"\000\022+\n\006accept\022\016.Acce" +
      "ptRequest\032\017.AcceptResponse\"\000\022+\n\006commit\022\016" +
      ".CommitRequest\032\017.CommitResponse\"\0002\241\001\n\017Ac" +
      "tivateServers\022C\n\016activateServer\022\026.Activa" +
      "teServerRequest\032\027.ActivateServerResponse" +
      "\"\000\022I\n\020deactivateServer\022\030.DeactivateServe" +
      "rRequest\032\031.DeactivateServerResponse\"\0002O\n" +
      "\014TnxPropagate\022?\n\024propagateTransaction\022\027." +
      "TransactionInputConfig\032\014.TxnResponse\"\0002\373" +
      "\001\n\010Commands\022/\n\014printBalance\022\r.CommandInp" +
      "ut\032\016.CommandOutput\"\000\022+\n\010printLog\022\r.Comma" +
      "ndInput\032\016.CommandOutput\"\000\022*\n\007printDB\022\r.C" +
      "ommandInput\032\016.CommandOutput\"\000\022.\n\013Perform" +
      "ance\022\r.CommandInput\032\016.CommandOutput\"\000\0225\n" +
      "\022printClientBalance\022\r.CommandInput\032\016.Com" +
      "mandOutput\"\0002e\n\010database\022-\n\004save\022\020.DataS" +
      "aveRequest\032\021.DataSaveResponse\"\000\022*\n\003get\022\017" +
      ".DataGetRequest\032\020.DataGetResponse\"\000B\024\n\020o" +
      "rg.cse535.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_TransactionInputConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionInputConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionInputConfig_descriptor,
        new java.lang.String[] { "SetNumber", "Transaction", "ServerNames", });
    internal_static_TxnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TxnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_PrepareRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareRequest_descriptor,
        new java.lang.String[] { "ProposalNumber", "ProcessId", "Timestamp", });
    internal_static_PrepareResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PrepareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareResponse_descriptor,
        new java.lang.String[] { "ProposalNumber", "ProcessId", "Transactions", "AcceptNumProposalNumber", "AcceptNumProcessId", "AcceptVal", "Success", });
    internal_static_AcceptRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_AcceptRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptRequest_descriptor,
        new java.lang.String[] { "ProposalNumber", "ProcessId", "Timestamp", "TransactionsToAccept", "SyncBlocks", "NeedsSync", });
    internal_static_AcceptRequest_SyncBlocksEntry_descriptor =
      internal_static_AcceptRequest_descriptor.getNestedTypes().get(0);
    internal_static_AcceptRequest_SyncBlocksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptRequest_SyncBlocksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_AcceptResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AcceptResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptResponse_descriptor,
        new java.lang.String[] { "ProposalNumber", "ProcessId", "AcceptedServerName", "Success", });
    internal_static_CommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitRequest_descriptor,
        new java.lang.String[] { "ProposalNumber", "ProcessId", "Block", "Timestamp", });
    internal_static_CommitResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitResponse_descriptor,
        new java.lang.String[] { "ProposalNumber", "Success", "ProcessId", "AcceptedServerName", });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", "Timestamp", "TransactionHash", "TransactionNum", });
    internal_static_BlockOfTransactions_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_BlockOfTransactions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlockOfTransactions_descriptor,
        new java.lang.String[] { "Transactions", "BlockNum", "BlockCommitTime", "BlockHash", "Leader", "TermNumber", });
    internal_static_ActivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ActivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_ActivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ActivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_DeactivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_DeactivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_DeactivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DeactivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_CommandInput_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CommandInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandInput_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_CommandOutput_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_CommandOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandOutput_descriptor,
        new java.lang.String[] { "Output", });
    internal_static_DatabaseSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_DatabaseSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseSnapshot_descriptor,
        new java.lang.String[] { "AcceptedProposalNumber", "AcceptedServerId", "AcceptedBlockOfTransactions", "AccountBalance", "CommittedAccountBalance", "CommittedProposalNumber", "Blocks", "BalanceAfterCommit", "ClientBalancesAfterCommit", "TransactionsProcessed", "TransactionsCommitted", "TransactionsAborted", "CurrentProposalNumber", "CurrentServerId", "IncomingTransactionsQueue", "LocalTransactionLog", "LeaderTransactionLog", "LastPrepareAckTimestamp", "LastPrepareAckServer", "LastAcceptAckTimestamp", "LastCommitTimestamp", "ProcessedTransactionsSet", "TimeTakenToExecuteMap", "LeaderBalanceAfterTransactions", });
    internal_static_DatabaseSnapshot_BlocksEntry_descriptor =
      internal_static_DatabaseSnapshot_descriptor.getNestedTypes().get(0);
    internal_static_DatabaseSnapshot_BlocksEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseSnapshot_BlocksEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DatabaseSnapshot_BalanceAfterCommitEntry_descriptor =
      internal_static_DatabaseSnapshot_descriptor.getNestedTypes().get(1);
    internal_static_DatabaseSnapshot_BalanceAfterCommitEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseSnapshot_BalanceAfterCommitEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DatabaseSnapshot_ClientBalancesAfterCommitEntry_descriptor =
      internal_static_DatabaseSnapshot_descriptor.getNestedTypes().get(2);
    internal_static_DatabaseSnapshot_ClientBalancesAfterCommitEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseSnapshot_ClientBalancesAfterCommitEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DatabaseSnapshot_TimeTakenToExecuteMapEntry_descriptor =
      internal_static_DatabaseSnapshot_descriptor.getNestedTypes().get(3);
    internal_static_DatabaseSnapshot_TimeTakenToExecuteMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatabaseSnapshot_TimeTakenToExecuteMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TimeTakenMask_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_TimeTakenMask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeTakenMask_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", });
    internal_static_DataSaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_DataSaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataSaveRequest_descriptor,
        new java.lang.String[] { "ServerName", "Snapshot", });
    internal_static_DataSaveResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_DataSaveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataSaveResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_DataGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_DataGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataGetRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_DataGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_DataGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataGetResponse_descriptor,
        new java.lang.String[] { "Snapshot", "Success", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
