// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

/**
 * Protobuf type {@code BlockOfTransactions}
 */
public  final class BlockOfTransactions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BlockOfTransactions)
    BlockOfTransactionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockOfTransactions.newBuilder() to construct.
  private BlockOfTransactions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockOfTransactions() {
    transactions_ = java.util.Collections.emptyList();
    blockNum_ = 0;
    blockHash_ = "";
    leader_ = "";
    termNumber_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BlockOfTransactions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              transactions_ = new java.util.ArrayList<org.cse535.proto.Transaction>();
              mutable_bitField0_ |= 0x00000001;
            }
            transactions_.add(
                input.readMessage(org.cse535.proto.Transaction.parser(), extensionRegistry));
            break;
          }
          case 16: {

            blockNum_ = input.readInt32();
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (blockCommitTime_ != null) {
              subBuilder = blockCommitTime_.toBuilder();
            }
            blockCommitTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(blockCommitTime_);
              blockCommitTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            blockHash_ = s;
            break;
          }
          case 40: {

            termNumber_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            leader_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        transactions_ = java.util.Collections.unmodifiableList(transactions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_BlockOfTransactions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_BlockOfTransactions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.BlockOfTransactions.class, org.cse535.proto.BlockOfTransactions.Builder.class);
  }

  private int bitField0_;
  public static final int TRANSACTIONS_FIELD_NUMBER = 1;
  private java.util.List<org.cse535.proto.Transaction> transactions_;
  /**
   * <code>repeated .Transaction transactions = 1;</code>
   */
  public java.util.List<org.cse535.proto.Transaction> getTransactionsList() {
    return transactions_;
  }
  /**
   * <code>repeated .Transaction transactions = 1;</code>
   */
  public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getTransactionsOrBuilderList() {
    return transactions_;
  }
  /**
   * <code>repeated .Transaction transactions = 1;</code>
   */
  public int getTransactionsCount() {
    return transactions_.size();
  }
  /**
   * <code>repeated .Transaction transactions = 1;</code>
   */
  public org.cse535.proto.Transaction getTransactions(int index) {
    return transactions_.get(index);
  }
  /**
   * <code>repeated .Transaction transactions = 1;</code>
   */
  public org.cse535.proto.TransactionOrBuilder getTransactionsOrBuilder(
      int index) {
    return transactions_.get(index);
  }

  public static final int BLOCKNUM_FIELD_NUMBER = 2;
  private int blockNum_;
  /**
   * <code>int32 blockNum = 2;</code>
   */
  public int getBlockNum() {
    return blockNum_;
  }

  public static final int BLOCKCOMMITTIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp blockCommitTime_;
  /**
   * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
   */
  public boolean hasBlockCommitTime() {
    return blockCommitTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
   */
  public com.google.protobuf.Timestamp getBlockCommitTime() {
    return blockCommitTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : blockCommitTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getBlockCommitTimeOrBuilder() {
    return getBlockCommitTime();
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 4;
  private volatile java.lang.Object blockHash_;
  /**
   * <code>string blockHash = 4;</code>
   */
  public java.lang.String getBlockHash() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockHash = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBlockHashBytes() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEADER_FIELD_NUMBER = 6;
  private volatile java.lang.Object leader_;
  /**
   * <code>string leader = 6;</code>
   */
  public java.lang.String getLeader() {
    java.lang.Object ref = leader_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leader_ = s;
      return s;
    }
  }
  /**
   * <code>string leader = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLeaderBytes() {
    java.lang.Object ref = leader_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leader_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERMNUMBER_FIELD_NUMBER = 5;
  private int termNumber_;
  /**
   * <pre>
   * proposal Number
   * </pre>
   *
   * <code>int32 termNumber = 5;</code>
   */
  public int getTermNumber() {
    return termNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < transactions_.size(); i++) {
      output.writeMessage(1, transactions_.get(i));
    }
    if (blockNum_ != 0) {
      output.writeInt32(2, blockNum_);
    }
    if (blockCommitTime_ != null) {
      output.writeMessage(3, getBlockCommitTime());
    }
    if (!getBlockHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, blockHash_);
    }
    if (termNumber_ != 0) {
      output.writeInt32(5, termNumber_);
    }
    if (!getLeaderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, leader_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < transactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, transactions_.get(i));
    }
    if (blockNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, blockNum_);
    }
    if (blockCommitTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBlockCommitTime());
    }
    if (!getBlockHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, blockHash_);
    }
    if (termNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, termNumber_);
    }
    if (!getLeaderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, leader_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.BlockOfTransactions)) {
      return super.equals(obj);
    }
    org.cse535.proto.BlockOfTransactions other = (org.cse535.proto.BlockOfTransactions) obj;

    boolean result = true;
    result = result && getTransactionsList()
        .equals(other.getTransactionsList());
    result = result && (getBlockNum()
        == other.getBlockNum());
    result = result && (hasBlockCommitTime() == other.hasBlockCommitTime());
    if (hasBlockCommitTime()) {
      result = result && getBlockCommitTime()
          .equals(other.getBlockCommitTime());
    }
    result = result && getBlockHash()
        .equals(other.getBlockHash());
    result = result && getLeader()
        .equals(other.getLeader());
    result = result && (getTermNumber()
        == other.getTermNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTransactionsCount() > 0) {
      hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    hash = (37 * hash) + BLOCKNUM_FIELD_NUMBER;
    hash = (53 * hash) + getBlockNum();
    if (hasBlockCommitTime()) {
      hash = (37 * hash) + BLOCKCOMMITTIME_FIELD_NUMBER;
      hash = (53 * hash) + getBlockCommitTime().hashCode();
    }
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    hash = (37 * hash) + LEADER_FIELD_NUMBER;
    hash = (53 * hash) + getLeader().hashCode();
    hash = (37 * hash) + TERMNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getTermNumber();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.BlockOfTransactions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.BlockOfTransactions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.BlockOfTransactions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.BlockOfTransactions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.BlockOfTransactions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BlockOfTransactions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BlockOfTransactions)
      org.cse535.proto.BlockOfTransactionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_BlockOfTransactions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_BlockOfTransactions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.BlockOfTransactions.class, org.cse535.proto.BlockOfTransactions.Builder.class);
    }

    // Construct using org.cse535.proto.BlockOfTransactions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transactionsBuilder_.clear();
      }
      blockNum_ = 0;

      if (blockCommitTimeBuilder_ == null) {
        blockCommitTime_ = null;
      } else {
        blockCommitTime_ = null;
        blockCommitTimeBuilder_ = null;
      }
      blockHash_ = "";

      leader_ = "";

      termNumber_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_BlockOfTransactions_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.BlockOfTransactions getDefaultInstanceForType() {
      return org.cse535.proto.BlockOfTransactions.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.BlockOfTransactions build() {
      org.cse535.proto.BlockOfTransactions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.BlockOfTransactions buildPartial() {
      org.cse535.proto.BlockOfTransactions result = new org.cse535.proto.BlockOfTransactions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (transactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactions_ = transactions_;
      } else {
        result.transactions_ = transactionsBuilder_.build();
      }
      result.blockNum_ = blockNum_;
      if (blockCommitTimeBuilder_ == null) {
        result.blockCommitTime_ = blockCommitTime_;
      } else {
        result.blockCommitTime_ = blockCommitTimeBuilder_.build();
      }
      result.blockHash_ = blockHash_;
      result.leader_ = leader_;
      result.termNumber_ = termNumber_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.BlockOfTransactions) {
        return mergeFrom((org.cse535.proto.BlockOfTransactions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.BlockOfTransactions other) {
      if (other == org.cse535.proto.BlockOfTransactions.getDefaultInstance()) return this;
      if (transactionsBuilder_ == null) {
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
      } else {
        if (!other.transactions_.isEmpty()) {
          if (transactionsBuilder_.isEmpty()) {
            transactionsBuilder_.dispose();
            transactionsBuilder_ = null;
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsFieldBuilder() : null;
          } else {
            transactionsBuilder_.addAllMessages(other.transactions_);
          }
        }
      }
      if (other.getBlockNum() != 0) {
        setBlockNum(other.getBlockNum());
      }
      if (other.hasBlockCommitTime()) {
        mergeBlockCommitTime(other.getBlockCommitTime());
      }
      if (!other.getBlockHash().isEmpty()) {
        blockHash_ = other.blockHash_;
        onChanged();
      }
      if (!other.getLeader().isEmpty()) {
        leader_ = other.leader_;
        onChanged();
      }
      if (other.getTermNumber() != 0) {
        setTermNumber(other.getTermNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.BlockOfTransactions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.BlockOfTransactions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.cse535.proto.Transaction> transactions_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        transactions_ = new java.util.ArrayList<org.cse535.proto.Transaction>(transactions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> transactionsBuilder_;

    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<org.cse535.proto.Transaction> getTransactionsList() {
      if (transactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactions_);
      } else {
        return transactionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public int getTransactionsCount() {
      if (transactionsBuilder_ == null) {
        return transactions_.size();
      } else {
        return transactionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public org.cse535.proto.Transaction getTransactions(int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);
      } else {
        return transactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder setTransactions(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder setTransactions(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder addTransactions(org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder addTransactions(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(index, value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder addTransactions(
        org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder addTransactions(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder addAllTransactions(
        java.lang.Iterable<? extends org.cse535.proto.Transaction> values) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
      } else {
        transactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder clearTransactions() {
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public Builder removeTransactions(int index) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.remove(index);
        onChanged();
      } else {
        transactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public org.cse535.proto.Transaction.Builder getTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public org.cse535.proto.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);  } else {
        return transactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
         getTransactionsOrBuilderList() {
      if (transactionsBuilder_ != null) {
        return transactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactions_);
      }
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsBuilder() {
      return getTransactionsFieldBuilder().addBuilder(
          org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().addBuilder(
          index, org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .Transaction transactions = 1;</code>
     */
    public java.util.List<org.cse535.proto.Transaction.Builder> 
         getTransactionsBuilderList() {
      return getTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> 
        getTransactionsFieldBuilder() {
      if (transactionsBuilder_ == null) {
        transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder>(
                transactions_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        transactions_ = null;
      }
      return transactionsBuilder_;
    }

    private int blockNum_ ;
    /**
     * <code>int32 blockNum = 2;</code>
     */
    public int getBlockNum() {
      return blockNum_;
    }
    /**
     * <code>int32 blockNum = 2;</code>
     */
    public Builder setBlockNum(int value) {
      
      blockNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 blockNum = 2;</code>
     */
    public Builder clearBlockNum() {
      
      blockNum_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp blockCommitTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> blockCommitTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public boolean hasBlockCommitTime() {
      return blockCommitTimeBuilder_ != null || blockCommitTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public com.google.protobuf.Timestamp getBlockCommitTime() {
      if (blockCommitTimeBuilder_ == null) {
        return blockCommitTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : blockCommitTime_;
      } else {
        return blockCommitTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public Builder setBlockCommitTime(com.google.protobuf.Timestamp value) {
      if (blockCommitTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blockCommitTime_ = value;
        onChanged();
      } else {
        blockCommitTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public Builder setBlockCommitTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (blockCommitTimeBuilder_ == null) {
        blockCommitTime_ = builderForValue.build();
        onChanged();
      } else {
        blockCommitTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public Builder mergeBlockCommitTime(com.google.protobuf.Timestamp value) {
      if (blockCommitTimeBuilder_ == null) {
        if (blockCommitTime_ != null) {
          blockCommitTime_ =
            com.google.protobuf.Timestamp.newBuilder(blockCommitTime_).mergeFrom(value).buildPartial();
        } else {
          blockCommitTime_ = value;
        }
        onChanged();
      } else {
        blockCommitTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public Builder clearBlockCommitTime() {
      if (blockCommitTimeBuilder_ == null) {
        blockCommitTime_ = null;
        onChanged();
      } else {
        blockCommitTime_ = null;
        blockCommitTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getBlockCommitTimeBuilder() {
      
      onChanged();
      return getBlockCommitTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBlockCommitTimeOrBuilder() {
      if (blockCommitTimeBuilder_ != null) {
        return blockCommitTimeBuilder_.getMessageOrBuilder();
      } else {
        return blockCommitTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : blockCommitTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp blockCommitTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getBlockCommitTimeFieldBuilder() {
      if (blockCommitTimeBuilder_ == null) {
        blockCommitTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getBlockCommitTime(),
                getParentForChildren(),
                isClean());
        blockCommitTime_ = null;
      }
      return blockCommitTimeBuilder_;
    }

    private java.lang.Object blockHash_ = "";
    /**
     * <code>string blockHash = 4;</code>
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blockHash = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockHash = 4;</code>
     */
    public Builder setBlockHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 4;</code>
     */
    public Builder clearBlockHash() {
      
      blockHash_ = getDefaultInstance().getBlockHash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 4;</code>
     */
    public Builder setBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockHash_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object leader_ = "";
    /**
     * <code>string leader = 6;</code>
     */
    public java.lang.String getLeader() {
      java.lang.Object ref = leader_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leader_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leader = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderBytes() {
      java.lang.Object ref = leader_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leader_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leader = 6;</code>
     */
    public Builder setLeader(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leader_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string leader = 6;</code>
     */
    public Builder clearLeader() {
      
      leader_ = getDefaultInstance().getLeader();
      onChanged();
      return this;
    }
    /**
     * <code>string leader = 6;</code>
     */
    public Builder setLeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leader_ = value;
      onChanged();
      return this;
    }

    private int termNumber_ ;
    /**
     * <pre>
     * proposal Number
     * </pre>
     *
     * <code>int32 termNumber = 5;</code>
     */
    public int getTermNumber() {
      return termNumber_;
    }
    /**
     * <pre>
     * proposal Number
     * </pre>
     *
     * <code>int32 termNumber = 5;</code>
     */
    public Builder setTermNumber(int value) {
      
      termNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * proposal Number
     * </pre>
     *
     * <code>int32 termNumber = 5;</code>
     */
    public Builder clearTermNumber() {
      
      termNumber_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BlockOfTransactions)
  }

  // @@protoc_insertion_point(class_scope:BlockOfTransactions)
  private static final org.cse535.proto.BlockOfTransactions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.BlockOfTransactions();
  }

  public static org.cse535.proto.BlockOfTransactions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockOfTransactions>
      PARSER = new com.google.protobuf.AbstractParser<BlockOfTransactions>() {
    @java.lang.Override
    public BlockOfTransactions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BlockOfTransactions(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BlockOfTransactions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockOfTransactions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.BlockOfTransactions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

