// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface CommitBlockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommitBlockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string approverName = 2;</code>
   */
  java.lang.String getApproverName();
  /**
   * <code>string approverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getApproverNameBytes();

  /**
   * <code>int32 blockNum = 3;</code>
   */
  int getBlockNum();
}
