// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

/**
 * Protobuf type {@code CommitBlockRequest}
 */
public  final class CommitBlockRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CommitBlockRequest)
    CommitBlockRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommitBlockRequest.newBuilder() to construct.
  private CommitBlockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommitBlockRequest() {
    leaderServerName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommitBlockRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.cse535.proto.BlockOfTransactions.Builder subBuilder = null;
            if (block_ != null) {
              subBuilder = block_.toBuilder();
            }
            block_ = input.readMessage(org.cse535.proto.BlockOfTransactions.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(block_);
              block_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            leaderServerName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.PaxosOuterClass.internal_static_CommitBlockRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.PaxosOuterClass.internal_static_CommitBlockRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.CommitBlockRequest.class, org.cse535.proto.CommitBlockRequest.Builder.class);
  }

  public static final int BLOCK_FIELD_NUMBER = 1;
  private org.cse535.proto.BlockOfTransactions block_;
  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  public boolean hasBlock() {
    return block_ != null;
  }
  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  public org.cse535.proto.BlockOfTransactions getBlock() {
    return block_ == null ? org.cse535.proto.BlockOfTransactions.getDefaultInstance() : block_;
  }
  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  public org.cse535.proto.BlockOfTransactionsOrBuilder getBlockOrBuilder() {
    return getBlock();
  }

  public static final int LEADERSERVERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object leaderServerName_;
  /**
   * <code>string leaderServerName = 2;</code>
   */
  public java.lang.String getLeaderServerName() {
    java.lang.Object ref = leaderServerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderServerName_ = s;
      return s;
    }
  }
  /**
   * <code>string leaderServerName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLeaderServerNameBytes() {
    java.lang.Object ref = leaderServerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderServerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (block_ != null) {
      output.writeMessage(1, getBlock());
    }
    if (!getLeaderServerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderServerName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (block_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBlock());
    }
    if (!getLeaderServerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderServerName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.CommitBlockRequest)) {
      return super.equals(obj);
    }
    org.cse535.proto.CommitBlockRequest other = (org.cse535.proto.CommitBlockRequest) obj;

    boolean result = true;
    result = result && (hasBlock() == other.hasBlock());
    if (hasBlock()) {
      result = result && getBlock()
          .equals(other.getBlock());
    }
    result = result && getLeaderServerName()
        .equals(other.getLeaderServerName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBlock()) {
      hash = (37 * hash) + BLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getBlock().hashCode();
    }
    hash = (37 * hash) + LEADERSERVERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderServerName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.CommitBlockRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.CommitBlockRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.CommitBlockRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.CommitBlockRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.CommitBlockRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CommitBlockRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CommitBlockRequest)
      org.cse535.proto.CommitBlockRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.PaxosOuterClass.internal_static_CommitBlockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.PaxosOuterClass.internal_static_CommitBlockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.CommitBlockRequest.class, org.cse535.proto.CommitBlockRequest.Builder.class);
    }

    // Construct using org.cse535.proto.CommitBlockRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (blockBuilder_ == null) {
        block_ = null;
      } else {
        block_ = null;
        blockBuilder_ = null;
      }
      leaderServerName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.PaxosOuterClass.internal_static_CommitBlockRequest_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.CommitBlockRequest getDefaultInstanceForType() {
      return org.cse535.proto.CommitBlockRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.CommitBlockRequest build() {
      org.cse535.proto.CommitBlockRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.CommitBlockRequest buildPartial() {
      org.cse535.proto.CommitBlockRequest result = new org.cse535.proto.CommitBlockRequest(this);
      if (blockBuilder_ == null) {
        result.block_ = block_;
      } else {
        result.block_ = blockBuilder_.build();
      }
      result.leaderServerName_ = leaderServerName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.CommitBlockRequest) {
        return mergeFrom((org.cse535.proto.CommitBlockRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.CommitBlockRequest other) {
      if (other == org.cse535.proto.CommitBlockRequest.getDefaultInstance()) return this;
      if (other.hasBlock()) {
        mergeBlock(other.getBlock());
      }
      if (!other.getLeaderServerName().isEmpty()) {
        leaderServerName_ = other.leaderServerName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.CommitBlockRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.CommitBlockRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.cse535.proto.BlockOfTransactions block_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder> blockBuilder_;
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public boolean hasBlock() {
      return blockBuilder_ != null || block_ != null;
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public org.cse535.proto.BlockOfTransactions getBlock() {
      if (blockBuilder_ == null) {
        return block_ == null ? org.cse535.proto.BlockOfTransactions.getDefaultInstance() : block_;
      } else {
        return blockBuilder_.getMessage();
      }
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public Builder setBlock(org.cse535.proto.BlockOfTransactions value) {
      if (blockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        block_ = value;
        onChanged();
      } else {
        blockBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public Builder setBlock(
        org.cse535.proto.BlockOfTransactions.Builder builderForValue) {
      if (blockBuilder_ == null) {
        block_ = builderForValue.build();
        onChanged();
      } else {
        blockBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public Builder mergeBlock(org.cse535.proto.BlockOfTransactions value) {
      if (blockBuilder_ == null) {
        if (block_ != null) {
          block_ =
            org.cse535.proto.BlockOfTransactions.newBuilder(block_).mergeFrom(value).buildPartial();
        } else {
          block_ = value;
        }
        onChanged();
      } else {
        blockBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public Builder clearBlock() {
      if (blockBuilder_ == null) {
        block_ = null;
        onChanged();
      } else {
        block_ = null;
        blockBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public org.cse535.proto.BlockOfTransactions.Builder getBlockBuilder() {
      
      onChanged();
      return getBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    public org.cse535.proto.BlockOfTransactionsOrBuilder getBlockOrBuilder() {
      if (blockBuilder_ != null) {
        return blockBuilder_.getMessageOrBuilder();
      } else {
        return block_ == null ?
            org.cse535.proto.BlockOfTransactions.getDefaultInstance() : block_;
      }
    }
    /**
     * <code>.BlockOfTransactions block = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder> 
        getBlockFieldBuilder() {
      if (blockBuilder_ == null) {
        blockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder>(
                getBlock(),
                getParentForChildren(),
                isClean());
        block_ = null;
      }
      return blockBuilder_;
    }

    private java.lang.Object leaderServerName_ = "";
    /**
     * <code>string leaderServerName = 2;</code>
     */
    public java.lang.String getLeaderServerName() {
      java.lang.Object ref = leaderServerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderServerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leaderServerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderServerNameBytes() {
      java.lang.Object ref = leaderServerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderServerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leaderServerName = 2;</code>
     */
    public Builder setLeaderServerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leaderServerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string leaderServerName = 2;</code>
     */
    public Builder clearLeaderServerName() {
      
      leaderServerName_ = getDefaultInstance().getLeaderServerName();
      onChanged();
      return this;
    }
    /**
     * <code>string leaderServerName = 2;</code>
     */
    public Builder setLeaderServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leaderServerName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CommitBlockRequest)
  }

  // @@protoc_insertion_point(class_scope:CommitBlockRequest)
  private static final org.cse535.proto.CommitBlockRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.CommitBlockRequest();
  }

  public static org.cse535.proto.CommitBlockRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitBlockRequest>
      PARSER = new com.google.protobuf.AbstractParser<CommitBlockRequest>() {
    @java.lang.Override
    public CommitBlockRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommitBlockRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommitBlockRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommitBlockRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.CommitBlockRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

