// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

public interface CommandInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommandInput)
    com.google.protobuf.MessageOrBuilder {
}
