// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface CommitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ballotNumber = 1;</code>
   */
  int getBallotNumber();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <code>repeated .Transaction transactions = 3;</code>
   */
  java.util.List<org.cse535.proto.Transaction> 
      getTransactionsList();
  /**
   * <code>repeated .Transaction transactions = 3;</code>
   */
  org.cse535.proto.Transaction getTransactions(int index);
  /**
   * <code>repeated .Transaction transactions = 3;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .Transaction transactions = 3;</code>
   */
  java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .Transaction transactions = 3;</code>
   */
  org.cse535.proto.TransactionOrBuilder getTransactionsOrBuilder(
      int index);
}
