// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface CommitBlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommitBlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  boolean hasBlock();
  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  org.cse535.proto.BlockOfTransactions getBlock();
  /**
   * <code>.BlockOfTransactions block = 1;</code>
   */
  org.cse535.proto.BlockOfTransactionsOrBuilder getBlockOrBuilder();

  /**
   * <code>string leaderServerName = 2;</code>
   */
  java.lang.String getLeaderServerName();
  /**
   * <code>string leaderServerName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLeaderServerNameBytes();
}
