// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

public interface DatabaseSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DatabaseSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 AcceptedProposalNumber = 1;</code>
   */
  int getAcceptedProposalNumber();

  /**
   * <code>string AcceptedServerId = 2;</code>
   */
  java.lang.String getAcceptedServerId();
  /**
   * <code>string AcceptedServerId = 2;</code>
   */
  com.google.protobuf.ByteString
      getAcceptedServerIdBytes();

  /**
   * <code>.BlockOfTransactions AcceptedBlockOfTransactions = 3;</code>
   */
  boolean hasAcceptedBlockOfTransactions();
  /**
   * <code>.BlockOfTransactions AcceptedBlockOfTransactions = 3;</code>
   */
  org.cse535.proto.BlockOfTransactions getAcceptedBlockOfTransactions();
  /**
   * <code>.BlockOfTransactions AcceptedBlockOfTransactions = 3;</code>
   */
  org.cse535.proto.BlockOfTransactionsOrBuilder getAcceptedBlockOfTransactionsOrBuilder();

  /**
   * <code>int32 AccountBalance = 4;</code>
   */
  int getAccountBalance();

  /**
   * <code>int32 CommittedAccountBalance = 5;</code>
   */
  int getCommittedAccountBalance();

  /**
   * <code>int32 CommittedProposalNumber = 6;</code>
   */
  int getCommittedProposalNumber();

  /**
   * <code>map&lt;int32, .BlockOfTransactions&gt; blocks = 7;</code>
   */
  int getBlocksCount();
  /**
   * <code>map&lt;int32, .BlockOfTransactions&gt; blocks = 7;</code>
   */
  boolean containsBlocks(
      int key);
  /**
   * Use {@link #getBlocksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
  getBlocks();
  /**
   * <code>map&lt;int32, .BlockOfTransactions&gt; blocks = 7;</code>
   */
  java.util.Map<java.lang.Integer, org.cse535.proto.BlockOfTransactions>
  getBlocksMap();
  /**
   * <code>map&lt;int32, .BlockOfTransactions&gt; blocks = 7;</code>
   */

  org.cse535.proto.BlockOfTransactions getBlocksOrDefault(
      int key,
      org.cse535.proto.BlockOfTransactions defaultValue);
  /**
   * <code>map&lt;int32, .BlockOfTransactions&gt; blocks = 7;</code>
   */

  org.cse535.proto.BlockOfTransactions getBlocksOrThrow(
      int key);

  /**
   * <code>map&lt;int32, int32&gt; balanceAfterCommit = 8;</code>
   */
  int getBalanceAfterCommitCount();
  /**
   * <code>map&lt;int32, int32&gt; balanceAfterCommit = 8;</code>
   */
  boolean containsBalanceAfterCommit(
      int key);
  /**
   * Use {@link #getBalanceAfterCommitMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getBalanceAfterCommit();
  /**
   * <code>map&lt;int32, int32&gt; balanceAfterCommit = 8;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getBalanceAfterCommitMap();
  /**
   * <code>map&lt;int32, int32&gt; balanceAfterCommit = 8;</code>
   */

  int getBalanceAfterCommitOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; balanceAfterCommit = 8;</code>
   */

  int getBalanceAfterCommitOrThrow(
      int key);

  /**
   * <code>map&lt;string, int32&gt; clientBalancesAfterCommit = 9;</code>
   */
  int getClientBalancesAfterCommitCount();
  /**
   * <code>map&lt;string, int32&gt; clientBalancesAfterCommit = 9;</code>
   */
  boolean containsClientBalancesAfterCommit(
      java.lang.String key);
  /**
   * Use {@link #getClientBalancesAfterCommitMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getClientBalancesAfterCommit();
  /**
   * <code>map&lt;string, int32&gt; clientBalancesAfterCommit = 9;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getClientBalancesAfterCommitMap();
  /**
   * <code>map&lt;string, int32&gt; clientBalancesAfterCommit = 9;</code>
   */

  int getClientBalancesAfterCommitOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; clientBalancesAfterCommit = 9;</code>
   */

  int getClientBalancesAfterCommitOrThrow(
      java.lang.String key);

  /**
   * <code>int32 transactionsProcessed = 10;</code>
   */
  int getTransactionsProcessed();

  /**
   * <code>int32 transactionsCommitted = 11;</code>
   */
  int getTransactionsCommitted();

  /**
   * <code>int32 transactionsAborted = 12;</code>
   */
  int getTransactionsAborted();

  /**
   * <code>int32 currentProposalNumber = 13;</code>
   */
  int getCurrentProposalNumber();

  /**
   * <code>string currentServerId = 14;</code>
   */
  java.lang.String getCurrentServerId();
  /**
   * <code>string currentServerId = 14;</code>
   */
  com.google.protobuf.ByteString
      getCurrentServerIdBytes();

  /**
   * <code>repeated .TransactionInputConfig incomingTransactionsQueue = 15;</code>
   */
  java.util.List<org.cse535.proto.TransactionInputConfig> 
      getIncomingTransactionsQueueList();
  /**
   * <code>repeated .TransactionInputConfig incomingTransactionsQueue = 15;</code>
   */
  org.cse535.proto.TransactionInputConfig getIncomingTransactionsQueue(int index);
  /**
   * <code>repeated .TransactionInputConfig incomingTransactionsQueue = 15;</code>
   */
  int getIncomingTransactionsQueueCount();
  /**
   * <code>repeated .TransactionInputConfig incomingTransactionsQueue = 15;</code>
   */
  java.util.List<? extends org.cse535.proto.TransactionInputConfigOrBuilder> 
      getIncomingTransactionsQueueOrBuilderList();
  /**
   * <code>repeated .TransactionInputConfig incomingTransactionsQueue = 15;</code>
   */
  org.cse535.proto.TransactionInputConfigOrBuilder getIncomingTransactionsQueueOrBuilder(
      int index);

  /**
   * <code>repeated .Transaction localTransactionLog = 16;</code>
   */
  java.util.List<org.cse535.proto.Transaction> 
      getLocalTransactionLogList();
  /**
   * <code>repeated .Transaction localTransactionLog = 16;</code>
   */
  org.cse535.proto.Transaction getLocalTransactionLog(int index);
  /**
   * <code>repeated .Transaction localTransactionLog = 16;</code>
   */
  int getLocalTransactionLogCount();
  /**
   * <code>repeated .Transaction localTransactionLog = 16;</code>
   */
  java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getLocalTransactionLogOrBuilderList();
  /**
   * <code>repeated .Transaction localTransactionLog = 16;</code>
   */
  org.cse535.proto.TransactionOrBuilder getLocalTransactionLogOrBuilder(
      int index);

  /**
   * <code>repeated .Transaction leaderTransactionLog = 17;</code>
   */
  java.util.List<org.cse535.proto.Transaction> 
      getLeaderTransactionLogList();
  /**
   * <code>repeated .Transaction leaderTransactionLog = 17;</code>
   */
  org.cse535.proto.Transaction getLeaderTransactionLog(int index);
  /**
   * <code>repeated .Transaction leaderTransactionLog = 17;</code>
   */
  int getLeaderTransactionLogCount();
  /**
   * <code>repeated .Transaction leaderTransactionLog = 17;</code>
   */
  java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getLeaderTransactionLogOrBuilderList();
  /**
   * <code>repeated .Transaction leaderTransactionLog = 17;</code>
   */
  org.cse535.proto.TransactionOrBuilder getLeaderTransactionLogOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp lastPrepareAckTimestamp = 18;</code>
   */
  boolean hasLastPrepareAckTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastPrepareAckTimestamp = 18;</code>
   */
  com.google.protobuf.Timestamp getLastPrepareAckTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastPrepareAckTimestamp = 18;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastPrepareAckTimestampOrBuilder();

  /**
   * <code>string lastPrepareAckServer = 19;</code>
   */
  java.lang.String getLastPrepareAckServer();
  /**
   * <code>string lastPrepareAckServer = 19;</code>
   */
  com.google.protobuf.ByteString
      getLastPrepareAckServerBytes();

  /**
   * <code>.google.protobuf.Timestamp lastAcceptAckTimestamp = 20;</code>
   */
  boolean hasLastAcceptAckTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastAcceptAckTimestamp = 20;</code>
   */
  com.google.protobuf.Timestamp getLastAcceptAckTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastAcceptAckTimestamp = 20;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastAcceptAckTimestampOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp lastCommitTimestamp = 21;</code>
   */
  boolean hasLastCommitTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastCommitTimestamp = 21;</code>
   */
  com.google.protobuf.Timestamp getLastCommitTimestamp();
  /**
   * <code>.google.protobuf.Timestamp lastCommitTimestamp = 21;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastCommitTimestampOrBuilder();

  /**
   * <code>repeated int32 processedTransactionsSet = 22;</code>
   */
  java.util.List<java.lang.Integer> getProcessedTransactionsSetList();
  /**
   * <code>repeated int32 processedTransactionsSet = 22;</code>
   */
  int getProcessedTransactionsSetCount();
  /**
   * <code>repeated int32 processedTransactionsSet = 22;</code>
   */
  int getProcessedTransactionsSet(int index);

  /**
   * <code>map&lt;int32, .TimeTakenMask&gt; timeTakenToExecuteMap = 23;</code>
   */
  int getTimeTakenToExecuteMapCount();
  /**
   * <code>map&lt;int32, .TimeTakenMask&gt; timeTakenToExecuteMap = 23;</code>
   */
  boolean containsTimeTakenToExecuteMap(
      int key);
  /**
   * Use {@link #getTimeTakenToExecuteMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, org.cse535.proto.TimeTakenMask>
  getTimeTakenToExecuteMap();
  /**
   * <code>map&lt;int32, .TimeTakenMask&gt; timeTakenToExecuteMap = 23;</code>
   */
  java.util.Map<java.lang.Integer, org.cse535.proto.TimeTakenMask>
  getTimeTakenToExecuteMapMap();
  /**
   * <code>map&lt;int32, .TimeTakenMask&gt; timeTakenToExecuteMap = 23;</code>
   */

  org.cse535.proto.TimeTakenMask getTimeTakenToExecuteMapOrDefault(
      int key,
      org.cse535.proto.TimeTakenMask defaultValue);
  /**
   * <code>map&lt;int32, .TimeTakenMask&gt; timeTakenToExecuteMap = 23;</code>
   */

  org.cse535.proto.TimeTakenMask getTimeTakenToExecuteMapOrThrow(
      int key);

  /**
   * <code>int32 LeaderBalanceAfterTransactions = 24;</code>
   */
  int getLeaderBalanceAfterTransactions();
}
