// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public final class PaxosOuterClass {
  private PaxosOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013paxos.proto\"&\n\016PrepareRequest\022\024\n\014ballo" +
      "tNumber\030\001 \001(\005\"8\n\017PrepareResponse\022\024\n\014ball" +
      "otNumber\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\"2\n\rAccep" +
      "tRequest\022\022\n\nproposalID\030\001 \001(\005\022\r\n\005value\030\002 " +
      "\001(\t\"]\n\016AcceptResponse\022\024\n\014ballotNumber\030\001 " +
      "\001(\005\022\017\n\007success\030\002 \001(\010\022\021\n\tacceptNum\030\003 \001(\005\022" +
      "\021\n\tacceptVal\030\004 \001(\005\"I\n\rCommitRequest\022\024\n\014b" +
      "allotNumber\030\001 \001(\005\022\"\n\014transactions\030\003 \003(\0132" +
      "\014.Transaction\"[\n\016CommitResponse\022\024\n\014ballo" +
      "tNumber\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\022\"\n\014transa" +
      "ctions\030\003 \003(\0132\014.Transaction\"+\n\013SyncReques" +
      "t\022\016\n\006syncID\030\001 \001(\005\022\014\n\004data\030\002 \001(\t\">\n\014SyncR" +
      "esponse\022\n\n\002id\030\001 \001(\005\022\"\n\014transactions\030\002 \003(" +
      "\0132\014.Transaction\"?\n\013Transaction\022\016\n\006sender" +
      "\030\001 \001(\t\022\020\n\010receiver\030\002 \001(\t\022\016\n\006amount\030\003 \001(\005" +
      "2\221\001\n\005Paxos\022.\n\007prepare\022\017.PrepareRequest\032\020" +
      ".PrepareResponse\"\000\022+\n\006accept\022\016.AcceptReq" +
      "uest\032\017.AcceptResponse\"\000\022+\n\006commit\022\016.Comm" +
      "itRequest\032\017.CommitResponse\"\0002r\n\022Transact" +
      "ionService\022.\n\016addTransaction\022\014.Transacti" +
      "on\032\014.Transaction\"\000\022,\n\013synchronize\022\014.Sync" +
      "Request\032\r.SyncResponse\"\000B\024\n\020org.cse535.p" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PrepareRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareRequest_descriptor,
        new java.lang.String[] { "BallotNumber", });
    internal_static_PrepareResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrepareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareResponse_descriptor,
        new java.lang.String[] { "BallotNumber", "Success", });
    internal_static_AcceptRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AcceptRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptRequest_descriptor,
        new java.lang.String[] { "ProposalID", "Value", });
    internal_static_AcceptResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AcceptResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptResponse_descriptor,
        new java.lang.String[] { "BallotNumber", "Success", "AcceptNum", "AcceptVal", });
    internal_static_CommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitRequest_descriptor,
        new java.lang.String[] { "BallotNumber", "Transactions", });
    internal_static_CommitResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitResponse_descriptor,
        new java.lang.String[] { "BallotNumber", "Success", "Transactions", });
    internal_static_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncRequest_descriptor,
        new java.lang.String[] { "SyncID", "Data", });
    internal_static_SyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SyncResponse_descriptor,
        new java.lang.String[] { "Id", "Transactions", });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
