// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

/**
 * Protobuf type {@code PrepareResponse}
 */
public  final class PrepareResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrepareResponse)
    PrepareResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrepareResponse.newBuilder() to construct.
  private PrepareResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrepareResponse() {
    proposalNumber_ = 0;
    processId_ = "";
    transactions_ = java.util.Collections.emptyList();
    acceptNumProposalNumber_ = 0;
    acceptNumProcessId_ = "";
    success_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PrepareResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            proposalNumber_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            processId_ = s;
            break;
          }
          case 24: {

            success_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              transactions_ = new java.util.ArrayList<org.cse535.proto.Transaction>();
              mutable_bitField0_ |= 0x00000004;
            }
            transactions_.add(
                input.readMessage(org.cse535.proto.Transaction.parser(), extensionRegistry));
            break;
          }
          case 40: {

            acceptNumProposalNumber_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            acceptNumProcessId_ = s;
            break;
          }
          case 58: {
            org.cse535.proto.BlockOfTransactions.Builder subBuilder = null;
            if (acceptVal_ != null) {
              subBuilder = acceptVal_.toBuilder();
            }
            acceptVal_ = input.readMessage(org.cse535.proto.BlockOfTransactions.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(acceptVal_);
              acceptVal_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        transactions_ = java.util.Collections.unmodifiableList(transactions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_PrepareResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.ApaxosOuterClass.internal_static_PrepareResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.PrepareResponse.class, org.cse535.proto.PrepareResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROPOSALNUMBER_FIELD_NUMBER = 1;
  private int proposalNumber_;
  /**
   * <code>int32 proposalNumber = 1;</code>
   */
  public int getProposalNumber() {
    return proposalNumber_;
  }

  public static final int PROCESSID_FIELD_NUMBER = 2;
  private volatile java.lang.Object processId_;
  /**
   * <code>string processId = 2;</code>
   */
  public java.lang.String getProcessId() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processId_ = s;
      return s;
    }
  }
  /**
   * <code>string processId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProcessIdBytes() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONS_FIELD_NUMBER = 4;
  private java.util.List<org.cse535.proto.Transaction> transactions_;
  /**
   * <pre>
   * response T(S) from accepting server
   * </pre>
   *
   * <code>repeated .Transaction transactions = 4;</code>
   */
  public java.util.List<org.cse535.proto.Transaction> getTransactionsList() {
    return transactions_;
  }
  /**
   * <pre>
   * response T(S) from accepting server
   * </pre>
   *
   * <code>repeated .Transaction transactions = 4;</code>
   */
  public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
      getTransactionsOrBuilderList() {
    return transactions_;
  }
  /**
   * <pre>
   * response T(S) from accepting server
   * </pre>
   *
   * <code>repeated .Transaction transactions = 4;</code>
   */
  public int getTransactionsCount() {
    return transactions_.size();
  }
  /**
   * <pre>
   * response T(S) from accepting server
   * </pre>
   *
   * <code>repeated .Transaction transactions = 4;</code>
   */
  public org.cse535.proto.Transaction getTransactions(int index) {
    return transactions_.get(index);
  }
  /**
   * <pre>
   * response T(S) from accepting server
   * </pre>
   *
   * <code>repeated .Transaction transactions = 4;</code>
   */
  public org.cse535.proto.TransactionOrBuilder getTransactionsOrBuilder(
      int index) {
    return transactions_.get(index);
  }

  public static final int ACCEPTNUMPROPOSALNUMBER_FIELD_NUMBER = 5;
  private int acceptNumProposalNumber_;
  /**
   * <pre>
   * previous AcceptNum
   * </pre>
   *
   * <code>int32 AcceptNumProposalNumber = 5;</code>
   */
  public int getAcceptNumProposalNumber() {
    return acceptNumProposalNumber_;
  }

  public static final int ACCEPTNUMPROCESSID_FIELD_NUMBER = 6;
  private volatile java.lang.Object acceptNumProcessId_;
  /**
   * <pre>
   * previous AcceptNum
   * </pre>
   *
   * <code>string AcceptNumProcessId = 6;</code>
   */
  public java.lang.String getAcceptNumProcessId() {
    java.lang.Object ref = acceptNumProcessId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      acceptNumProcessId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * previous AcceptNum
   * </pre>
   *
   * <code>string AcceptNumProcessId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAcceptNumProcessIdBytes() {
    java.lang.Object ref = acceptNumProcessId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      acceptNumProcessId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCEPTVAL_FIELD_NUMBER = 7;
  private org.cse535.proto.BlockOfTransactions acceptVal_;
  /**
   * <code>.BlockOfTransactions AcceptVal = 7;</code>
   */
  public boolean hasAcceptVal() {
    return acceptVal_ != null;
  }
  /**
   * <code>.BlockOfTransactions AcceptVal = 7;</code>
   */
  public org.cse535.proto.BlockOfTransactions getAcceptVal() {
    return acceptVal_ == null ? org.cse535.proto.BlockOfTransactions.getDefaultInstance() : acceptVal_;
  }
  /**
   * <code>.BlockOfTransactions AcceptVal = 7;</code>
   */
  public org.cse535.proto.BlockOfTransactionsOrBuilder getAcceptValOrBuilder() {
    return getAcceptVal();
  }

  public static final int SUCCESS_FIELD_NUMBER = 3;
  private boolean success_;
  /**
   * <code>bool success = 3;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (proposalNumber_ != 0) {
      output.writeInt32(1, proposalNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processId_);
    }
    if (success_ != false) {
      output.writeBool(3, success_);
    }
    for (int i = 0; i < transactions_.size(); i++) {
      output.writeMessage(4, transactions_.get(i));
    }
    if (acceptNumProposalNumber_ != 0) {
      output.writeInt32(5, acceptNumProposalNumber_);
    }
    if (!getAcceptNumProcessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, acceptNumProcessId_);
    }
    if (acceptVal_ != null) {
      output.writeMessage(7, getAcceptVal());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (proposalNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, proposalNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processId_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, success_);
    }
    for (int i = 0; i < transactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, transactions_.get(i));
    }
    if (acceptNumProposalNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, acceptNumProposalNumber_);
    }
    if (!getAcceptNumProcessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, acceptNumProcessId_);
    }
    if (acceptVal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAcceptVal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.PrepareResponse)) {
      return super.equals(obj);
    }
    org.cse535.proto.PrepareResponse other = (org.cse535.proto.PrepareResponse) obj;

    boolean result = true;
    result = result && (getProposalNumber()
        == other.getProposalNumber());
    result = result && getProcessId()
        .equals(other.getProcessId());
    result = result && getTransactionsList()
        .equals(other.getTransactionsList());
    result = result && (getAcceptNumProposalNumber()
        == other.getAcceptNumProposalNumber());
    result = result && getAcceptNumProcessId()
        .equals(other.getAcceptNumProcessId());
    result = result && (hasAcceptVal() == other.hasAcceptVal());
    if (hasAcceptVal()) {
      result = result && getAcceptVal()
          .equals(other.getAcceptVal());
    }
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROPOSALNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getProposalNumber();
    hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessId().hashCode();
    if (getTransactionsCount() > 0) {
      hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    hash = (37 * hash) + ACCEPTNUMPROPOSALNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptNumProposalNumber();
    hash = (37 * hash) + ACCEPTNUMPROCESSID_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptNumProcessId().hashCode();
    if (hasAcceptVal()) {
      hash = (37 * hash) + ACCEPTVAL_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptVal().hashCode();
    }
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.PrepareResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.PrepareResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PrepareResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrepareResponse)
      org.cse535.proto.PrepareResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_PrepareResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_PrepareResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.PrepareResponse.class, org.cse535.proto.PrepareResponse.Builder.class);
    }

    // Construct using org.cse535.proto.PrepareResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      proposalNumber_ = 0;

      processId_ = "";

      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        transactionsBuilder_.clear();
      }
      acceptNumProposalNumber_ = 0;

      acceptNumProcessId_ = "";

      if (acceptValBuilder_ == null) {
        acceptVal_ = null;
      } else {
        acceptVal_ = null;
        acceptValBuilder_ = null;
      }
      success_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.ApaxosOuterClass.internal_static_PrepareResponse_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse getDefaultInstanceForType() {
      return org.cse535.proto.PrepareResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse build() {
      org.cse535.proto.PrepareResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse buildPartial() {
      org.cse535.proto.PrepareResponse result = new org.cse535.proto.PrepareResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.proposalNumber_ = proposalNumber_;
      result.processId_ = processId_;
      if (transactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.transactions_ = transactions_;
      } else {
        result.transactions_ = transactionsBuilder_.build();
      }
      result.acceptNumProposalNumber_ = acceptNumProposalNumber_;
      result.acceptNumProcessId_ = acceptNumProcessId_;
      if (acceptValBuilder_ == null) {
        result.acceptVal_ = acceptVal_;
      } else {
        result.acceptVal_ = acceptValBuilder_.build();
      }
      result.success_ = success_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.PrepareResponse) {
        return mergeFrom((org.cse535.proto.PrepareResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.PrepareResponse other) {
      if (other == org.cse535.proto.PrepareResponse.getDefaultInstance()) return this;
      if (other.getProposalNumber() != 0) {
        setProposalNumber(other.getProposalNumber());
      }
      if (!other.getProcessId().isEmpty()) {
        processId_ = other.processId_;
        onChanged();
      }
      if (transactionsBuilder_ == null) {
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
      } else {
        if (!other.transactions_.isEmpty()) {
          if (transactionsBuilder_.isEmpty()) {
            transactionsBuilder_.dispose();
            transactionsBuilder_ = null;
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000004);
            transactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsFieldBuilder() : null;
          } else {
            transactionsBuilder_.addAllMessages(other.transactions_);
          }
        }
      }
      if (other.getAcceptNumProposalNumber() != 0) {
        setAcceptNumProposalNumber(other.getAcceptNumProposalNumber());
      }
      if (!other.getAcceptNumProcessId().isEmpty()) {
        acceptNumProcessId_ = other.acceptNumProcessId_;
        onChanged();
      }
      if (other.hasAcceptVal()) {
        mergeAcceptVal(other.getAcceptVal());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.PrepareResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.PrepareResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int proposalNumber_ ;
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public int getProposalNumber() {
      return proposalNumber_;
    }
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public Builder setProposalNumber(int value) {
      
      proposalNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 proposalNumber = 1;</code>
     */
    public Builder clearProposalNumber() {
      
      proposalNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object processId_ = "";
    /**
     * <code>string processId = 2;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder clearProcessId() {
      
      processId_ = getDefaultInstance().getProcessId();
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.cse535.proto.Transaction> transactions_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        transactions_ = new java.util.ArrayList<org.cse535.proto.Transaction>(transactions_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> transactionsBuilder_;

    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public java.util.List<org.cse535.proto.Transaction> getTransactionsList() {
      if (transactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactions_);
      } else {
        return transactionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public int getTransactionsCount() {
      if (transactionsBuilder_ == null) {
        return transactions_.size();
      } else {
        return transactionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public org.cse535.proto.Transaction getTransactions(int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);
      } else {
        return transactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder setTransactions(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder setTransactions(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder addTransactions(org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder addTransactions(
        int index, org.cse535.proto.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(index, value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder addTransactions(
        org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder addTransactions(
        int index, org.cse535.proto.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder addAllTransactions(
        java.lang.Iterable<? extends org.cse535.proto.Transaction> values) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
      } else {
        transactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder clearTransactions() {
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public Builder removeTransactions(int index) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.remove(index);
        onChanged();
      } else {
        transactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder getTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public org.cse535.proto.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);  } else {
        return transactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public java.util.List<? extends org.cse535.proto.TransactionOrBuilder> 
         getTransactionsOrBuilderList() {
      if (transactionsBuilder_ != null) {
        return transactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactions_);
      }
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsBuilder() {
      return getTransactionsFieldBuilder().addBuilder(
          org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder addTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().addBuilder(
          index, org.cse535.proto.Transaction.getDefaultInstance());
    }
    /**
     * <pre>
     * response T(S) from accepting server
     * </pre>
     *
     * <code>repeated .Transaction transactions = 4;</code>
     */
    public java.util.List<org.cse535.proto.Transaction.Builder> 
         getTransactionsBuilderList() {
      return getTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> 
        getTransactionsFieldBuilder() {
      if (transactionsBuilder_ == null) {
        transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder>(
                transactions_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        transactions_ = null;
      }
      return transactionsBuilder_;
    }

    private int acceptNumProposalNumber_ ;
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>int32 AcceptNumProposalNumber = 5;</code>
     */
    public int getAcceptNumProposalNumber() {
      return acceptNumProposalNumber_;
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>int32 AcceptNumProposalNumber = 5;</code>
     */
    public Builder setAcceptNumProposalNumber(int value) {
      
      acceptNumProposalNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>int32 AcceptNumProposalNumber = 5;</code>
     */
    public Builder clearAcceptNumProposalNumber() {
      
      acceptNumProposalNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object acceptNumProcessId_ = "";
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>string AcceptNumProcessId = 6;</code>
     */
    public java.lang.String getAcceptNumProcessId() {
      java.lang.Object ref = acceptNumProcessId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptNumProcessId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>string AcceptNumProcessId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptNumProcessIdBytes() {
      java.lang.Object ref = acceptNumProcessId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptNumProcessId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>string AcceptNumProcessId = 6;</code>
     */
    public Builder setAcceptNumProcessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      acceptNumProcessId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>string AcceptNumProcessId = 6;</code>
     */
    public Builder clearAcceptNumProcessId() {
      
      acceptNumProcessId_ = getDefaultInstance().getAcceptNumProcessId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * previous AcceptNum
     * </pre>
     *
     * <code>string AcceptNumProcessId = 6;</code>
     */
    public Builder setAcceptNumProcessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      acceptNumProcessId_ = value;
      onChanged();
      return this;
    }

    private org.cse535.proto.BlockOfTransactions acceptVal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder> acceptValBuilder_;
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public boolean hasAcceptVal() {
      return acceptValBuilder_ != null || acceptVal_ != null;
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public org.cse535.proto.BlockOfTransactions getAcceptVal() {
      if (acceptValBuilder_ == null) {
        return acceptVal_ == null ? org.cse535.proto.BlockOfTransactions.getDefaultInstance() : acceptVal_;
      } else {
        return acceptValBuilder_.getMessage();
      }
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public Builder setAcceptVal(org.cse535.proto.BlockOfTransactions value) {
      if (acceptValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        acceptVal_ = value;
        onChanged();
      } else {
        acceptValBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public Builder setAcceptVal(
        org.cse535.proto.BlockOfTransactions.Builder builderForValue) {
      if (acceptValBuilder_ == null) {
        acceptVal_ = builderForValue.build();
        onChanged();
      } else {
        acceptValBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public Builder mergeAcceptVal(org.cse535.proto.BlockOfTransactions value) {
      if (acceptValBuilder_ == null) {
        if (acceptVal_ != null) {
          acceptVal_ =
            org.cse535.proto.BlockOfTransactions.newBuilder(acceptVal_).mergeFrom(value).buildPartial();
        } else {
          acceptVal_ = value;
        }
        onChanged();
      } else {
        acceptValBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public Builder clearAcceptVal() {
      if (acceptValBuilder_ == null) {
        acceptVal_ = null;
        onChanged();
      } else {
        acceptVal_ = null;
        acceptValBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public org.cse535.proto.BlockOfTransactions.Builder getAcceptValBuilder() {
      
      onChanged();
      return getAcceptValFieldBuilder().getBuilder();
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    public org.cse535.proto.BlockOfTransactionsOrBuilder getAcceptValOrBuilder() {
      if (acceptValBuilder_ != null) {
        return acceptValBuilder_.getMessageOrBuilder();
      } else {
        return acceptVal_ == null ?
            org.cse535.proto.BlockOfTransactions.getDefaultInstance() : acceptVal_;
      }
    }
    /**
     * <code>.BlockOfTransactions AcceptVal = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder> 
        getAcceptValFieldBuilder() {
      if (acceptValBuilder_ == null) {
        acceptValBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cse535.proto.BlockOfTransactions, org.cse535.proto.BlockOfTransactions.Builder, org.cse535.proto.BlockOfTransactionsOrBuilder>(
                getAcceptVal(),
                getParentForChildren(),
                isClean());
        acceptVal_ = null;
      }
      return acceptValBuilder_;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 3;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 3;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 3;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrepareResponse)
  }

  // @@protoc_insertion_point(class_scope:PrepareResponse)
  private static final org.cse535.proto.PrepareResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.PrepareResponse();
  }

  public static org.cse535.proto.PrepareResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrepareResponse>
      PARSER = new com.google.protobuf.AbstractParser<PrepareResponse>() {
    @java.lang.Override
    public PrepareResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PrepareResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PrepareResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrepareResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.PrepareResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

