// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface PrepareResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrepareResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ballotNumber = 1;</code>
   */
  int getBallotNumber();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
