// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface SyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 syncID = 1;</code>
   */
  int getSyncID();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
