// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apaxos.proto

package org.cse535.proto;

public interface TimeTakenMaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TimeTakenMask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 startTime = 1;</code>
   */
  long getStartTime();

  /**
   * <code>int64 endTime = 2;</code>
   */
  long getEndTime();
}
