// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos.proto

package org.cse535.proto;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string receiver = 2;</code>
   */
  java.lang.String getReceiver();
  /**
   * <code>string receiver = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>int32 amount = 3;</code>
   */
  int getAmount();
}
